### ISSUE TITLE
Add JSON encoding support for ObjectId

### ISSUE THREAD

**Issue by ganwumeng** [gonuit/dart_objectid#3]
# Problem
While trying to use
```dart
List<ObjectId> objectIdList = [...];
jsonEncode(objectIdList);
```
, throw an exception:
>Converting object to an encodable object failed: Instance of 'ObjectId'

# Solution
Add tojson and fromjson function

**Comment by gonuit** [comment]
Hi @ganwumeng, the `ObjectId.fromJson(json)` constructor (alias for `ObjectId.fromHexString(hexString)`) and the `toJson()` method were added in version 3.1.0.
